### ISSUE TITLE
Nearly there?

### ISSUE THREAD

**Issue by roffey** [lemariva/uPyEcho#2]
I'm trying to get this going on a spiram esp32 ttgo wrover module.
I have had to import a couple of different modules and change the rtc etc.
All is apparently working as I see no exception messages, and the date time displays correctly.
Goes into the main loop and displays Targets dict_keys([54, 55]) … does this mean I am actually close? I do have other Arduino fauxmo units running, but I wanted micropython running.
I shut down the other fauxmo units whilst 'finding devices' but to no luck.
Any help would be appreciated …. thanks

 
   
Author 
roffey commented 15 minutes ago 
now getting this reply error …
Got problem to send response function takes 1 positional arguments but 3 were given...
doing what I can with wireshark etc.... will keep plodding away, but a little help would be good :)

**Comment by lemariva** [comment]
It should respond something like this: https://youtu.be/kkF3HfXV59I?t=21 
I'll check it again this week. May be a library was updated, and the code needs some upgrade.

**Comment by roffey** [comment]
Hi …. Thank you very much for responding…..

I had an error created by a dbg message, which has now cleared that problem.

I had to use time.localtime() in place of gmtime in order to get the time date etc,

Although the time is I hour out.

I reduced the number of devices, just in case this was an issue.

 

I switched off all other fauxmo units before try a discover, but it refuses to be discovered. The following is how it runs….

 

 

Starting echo serviceList on separated thread

 

[0;32mI (4340) spi_master: Allocate TX buffer for DMA[0m

MicroPython v1.10-265-gfd523c53c on 2019-04-07; ESP32 module with ESP32

Type "help()" for more information.

>>> IP: 0 IP_ADD_MEMBERSHIP: 3 mreq: b'\xef\xff\xff\xfa\x00\x00\x00\x00'

Listening for UPnP broadcasts

got local address of 192.168.1.62

UPnP broadcast listener: new device registered

FauxMo device 'dmx' ready on 192.168.1.62:12340

Entering main loop

 

Targets dict_keys([54, 55])

Targets dict_keys([54, 55])

Targets dict_keys([54, 55])

………………………………………………………

>>> Targets dict_keys([54, 55])

Responding to search for dmx

Mon, 29 Apr 2019 11:10:39 GMT

Targets dict_keys([54, 55])

Targets dict_keys([54, 55])

 

If there is anything you can suggest, I would much appreciate it.

 

Thank you again….
